quarkus:
  datasource:
#    devservices:
#      image-name: "postgres:14.5"
    db-kind: postgresql
    username: postgres
    password: postgres
    reactive:
      url: "postgresql://${DB_HOST:localhost}:5432/blog_db"
      max-size: 20
    jdbc:
      url: "jdbc:postgresql://${DB_HOST:localhost}:5432/blog_db"
      max-size: 20
  liquibase:
    migrate-at-start: true
  http:
    auth:
      form:
        enabled: true
        login-page: /users/login
        post-location: /users/loginPost
        username-parameter: email
        password-parameter: password
        landing-page: /blog
greeting:
  name: "Bitelchus"